openapi: 3.0.0

paths:
  /transaction:
    post:
      summary: this endpoint saves information about a new transaction
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Transaction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST" #never changes
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

  /users:
    get:
      summary: list users that have an account
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUsers.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST" #never changes
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

  /transactions/{user}:
    get:
      summary: list transactions made by one user
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTransactionsFromUser.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST" #never changes
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"