AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
# SAM = Serverless Application Model

Resources:

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upb-lambda
      Handler: app.lambda_handler
      Runtime: python3.6
      CodeUri: build
      